### ISSUE TITLE
Ability to set Common Name on certificate

### ISSUE THREAD

**Issue by dtcooper** [JonasAlfredsson/docker-nginx-certbot#111]
Hi There,

At present, the Common Name on the certificate — the *first* domain argument for certbot — is set alphabetically. This is to say, all domain names are sorted alphabetically, and then the first one in that list is chosen as the Common Name on the X.509 certificate returned from certbot. I'm wondering if there could be a setting (or way of configuring a `.conf` file) to set the common name on a certificate. Thanks!

Useful for very old browsers that don't accept the Subject Alternative Name (SAN) extension and only accept a Common Name.

Thanks,

David

**Comment by JonasAlfredsson** [comment]
Hi dtcooper,

So if I understand this correctly certbot will use the first domain in the following request 

```
certbot ... -d "example.com" -d "www.example.com"
```
as the CN, and then list everything in the SAN like this?
```
CN: "example.com"
SAN: ["example.com", www.example.com"]
```

And you want to be able to choose which of the given domains is placed first in the request given to certbot because some old webbrowsers do not support the newer format?

---

Before digging further into this I must just ask you to elaborate on what you are trying to do a bit more. 
The reason for this is because according to [this](https://www.digicert.com/faq/subject-alternative-name-compatibility.htm) all major browsers have supported SAN since 2003, and if you are using an older browser than that to browse the internet today I would classify that as a very high security risk.

**Comment by dtcooper** [comment]
That's a correct understanding.

And truth be told: it's mostly for aesthetics. My use case is that u want the certificate's common name that shows up when user's inspect the certificate to be the "primary" domain.

**Comment by JonasAlfredsson** [comment]
I find aesthetics being a much more reasonable request than supporting almost 20 year old browsers :) 

However, I make use of the `sort -u` utility to not have to worry about creating duplicate requests to certbot, and make the code more readable, so right now I don't have any good suggestions on how to implement your suggestion without significantly changing the current parser and/or switching to a language with more features than bash. 
Both of those require quiet a lot of work, and I do not feel it is proportional to what we will gain, unfortunately.

**Comment by dtcooper** [comment]
Well, I think there's a `sort -u`-like method that preserves order, which would solve my use case. The first domain would be the common name.

I'll submit a PR today and if you like it, you can accept!

**Comment by JonasAlfredsson** [comment]
Absolutely, that sounds great! 
I am looking forward to it :)

**Comment by dtcooper** [comment]
Great! I'll look into that soon and fix them up. Thanks!
