### ISSUE TITLE
Add support for Gandi LiveDNS

### ISSUE THREAD

**Issue by 5V715** [JonasAlfredsson/docker-nginx-certbot#122]
there is  certbot plugin at https://github.com/obynio/certbot-plugin-gandi would be nice to see that

**Comment by JonasAlfredsson** [comment]
Hi 5V715,

I am a little bit hesitant to add this since it is not part of the [official dns plugins](https://eff-certbot.readthedocs.io/en/stable/using.html#dns-plugins) as far as I can tell. 
It also does not conform to the expected `pip install certbot-dns-<plugin>` format, so it will require special handling during the installation step and unless more people ask for this (or it becomes official) I would suggest you create your own Dockerfile:

```Dockerfile
FROM jonasal/nginx-certbot:3.1.2
RUN pip3 install -U certbot-plugin-gandi
ENV $CERTBOT_DNS_AUTHENTICATORS \
    gandi
```

I think that should be enough for it to work.

**Comment by JonasAlfredsson** [comment]
No response, reopen if this is still an issue.
