### ISSUE TITLE
Multiple domains support

### ISSUE THREAD

**Issue by robertsLando** [JonasAlfredsson/docker-nginx-certbot#138]
Hi @JonasAlfredsson ! Firstly thanks for this awesome docker image 🙏🏼 

I see your script is actaully smart enought to get all server names it finds in nginx conf files. Wondering if it works also with different domains or only for single domain and it's subdomains?

**Comment by JonasAlfredsson** [comment]
However, I would suggest you keep separate domains in separate certificate files in order to not "leak" information. A combined certificate would list that it is valid for:

- example.com
- sub.example.com
- somethingelse.com

which could then give the outsider information that these sites are probably owned by the same person.
