### ISSUE TITLE
Certbot suddenly stopped working without changes

### ISSUE THREAD

**Issue by jheathco** [JonasAlfredsson/docker-nginx-certbot#140]
Hi,

We've been using certbot successfully within our docker project for quite sometime, until suddenly it stopped working (no changes were made):

`nginx_1   | Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:`
`nginx_1   |   Domain: [removed]`
`nginx_1   |   Type:   unauthorized`
`nginx_1   |   Detail: 173.230.157.218: Invalid response from https://[removed]/.well-known/acme-challenge/K48Z53vo5LfJzxo1XnMHNiVK_UAY_NDEW4bNMzRCGwY: 403`

Not sure what to check as this was working just fine before...

**Comment by JonasAlfredsson** [comment]
Hi jheathco,

It sounds very strange that things just stopped working without any changes at all.
The error states that the Let's Encrypt servers are unable to reach a specific path on your setup since it is greeted with a 403 response. This could be because of there being some kind of login requirement, or it could be some kind of spam prevention software. 

I would start this debugging by first restarting the entire container (just because), and then take a closer look at all the .conf files being loaded. If you can post them here I can also analyze them to see if something is out of the ordinary.

After that I would try to see if I could CURL something in the /.well-known/acme-challenge path myself, to perhaps get a better look at where the request is being directed and then look in the Nginx logs.

**Comment by jheathco** [comment]
Hi,

Here's the gist: https://gist.github.com/jheathco/821c9ae3bd6d31b5b80c37a0acb92f23

I replaced the actual URL with "myurl".

I tried booting into nginx's container and opening port 81 to no avail... so not sure if that is the issue?

nginx is showing the access from the outside world:
`nginx_1   | 173.230.157.218 - - [15/Sep/2022:09:55:36 +0000] "GET /.well-known/acme-challenge/K48Z53vo5LfJzxo1XnMHNiVK_UAY_NDEW4bNMzRCGwY HTTP/1.1" 301 169 "-" "Wget/1.20.3 (linux-gnu)" "-"`

**Comment by jheathco** [comment]
Believe I've isolated the issue - it has to do with the port 80 interception and rerouting to HTTPS for rails.  Is there a suggested way of 80->443 redirection that still maintains the processing of the underlying redirector.conf for acme files?

**Comment by JonasAlfredsson** [comment]
Yeah, it was something like this I expected. The container has its own [redirector](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/src/nginx_conf.d/redirector.conf), so just remove the server block which intercepts port 80 and it should work.

**Comment by jheathco** [comment]
Run running this container in a local environment/testbed, how would you recommend (since I won't be running over SSL) processing rails requests on 80?

**Comment by JonasAlfredsson** [comment]
For what I have seen people just use the normal Nginx container in development (since all the features of this conatiner are then useless).

But there exists another possibility if you want to run HTTPS without internet access, and that is to read the section about [LOCAL_CA](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/advanced_usage.md#local-ca).

**Comment by jheathco** [comment]
Thank you!

**Comment by JonasAlfredsson** [comment]
No worries, glad I could help!
Do you need any more assistance or should this issue be closed?

**Comment by jheathco** [comment]
This can be closed - really appreciate the help.
