### ISSUE TITLE
Allow non https

### ISSUE THREAD

**Issue by igordeoliveirasa** [JonasAlfredsson/docker-nginx-certbot#143]
Hi! I would like to have https and some http (based on some paths) configured. How could I do that?

**Comment by JonasAlfredsson** [comment]
Hi igordeoliveirasa,

It is a conscious decision from my side to not allow insecure HTTP in this container, and I see no reason why one would want that.

If you are looking to serve HTTP I would probably recommend the base Nginx image.

**Comment by igordeoliveirasa** [comment]
Hi Jonas!

Its because Im implementing some payment operations using a third party payment gateway. This gateway uses webhooks to tell me payment statuses/events... Even using payment gateway's sandbox credentials, they cant reach my https endpoint because of self signed/staging/local CA development environment,.. Do you have any trick? Thanks!

**Comment by JonasAlfredsson** [comment]
Without knowing anything about the data these webhooks provide I would be very concerned of a service which would allow sending payment information in the clear today. 

How do you set up your staging/development environment? Du you have a DNS name pointing to this which is different than your production one? Because then you could just request proper certificates to your staging instance as well.

**Comment by igordeoliveirasa** [comment]
Jonas,

For development I use something like: api.myapp.localhost ...
I also use have myapp.duckdns.org configured together,.. But I cant set those *.localhost to stage/local-ca while duckdns.org proper certificate... If it is possible the problems will be solved!

**Comment by JonasAlfredsson** [comment]
Do you have to use *.localhost on your development instance or can you set up a domain like dev-myapp.duckdns.org so you can get proper certificates for it?
Because what domain/URL does the payment gateway use to communicate back to your development instance, or is the gateway app running locally on your machine as well?

**Comment by igordeoliveirasa** [comment]
Payment gateway uses myapp.duckdns.org/payment/id/notifications... But I also need to use *.localhost in order to facilitade multiple microservices development naming/port/routes..

**Comment by igordeoliveirasa** [comment]
Jonas, I use *.localhost because I have multiple microservices,.. And its easier to use this kind of domain. But it does not allow non-staging/non-local-ca.... But in order to give remote access to payment gateway I tried *.duckdns.org ... But since container is configured to use local-ca the payment gateway cant reach...

**Comment by JonasAlfredsson** [comment]
I am sorry, but I am having a difficult time visualizing how your traffic flows without seeing any config files. 

If you cannot use HTTPS then I suggest you replace this image with the base Nginx one and disable SSL in the configuration files. Beyond that it should be a drop in replacement as I have tried to make as few modifications as possible between the two images.

**Comment by JonasAlfredsson** [comment]
Are you still struggling with this, or have you found a workaround?

**Comment by JonasAlfredsson** [comment]
I will close this now, and you can reopen it if you still need help.

**Comment by plohoj** [comment]
I want to add my comment about using this image without HTTPS.

I was looking for a simple docker image and decided to try this one because it has a simple setup for automatic certbot updates.
I am unfamiliar with network infrastructures. I don't use this image for production projects. I have tried using this image for simple home purposes.
I want to set up Home Assistant with access from the internet and of course with SSL certificate.
In addition, in the same nginx home server I want to redirect simple services in the local network. Such as Portainer for example _`(portainer.local)`_.
Inside my local network I don't need HTTPS and I don't want to have a domain name known outside my local network.

I understand that the repository author may have purposely avoided HTTP for security reasons. I just want to share my use case. I even agree to some additional requirements like setting an environment variable to make sure I understand the risks involved. And even if with this variable the logs will be filled with warnings with huge letters.

Or at least, please add a warning in the README that this image does not allow using HTTP. So that people passing by, like me, don't waste their time learning a way that doesn't work for them

**Comment by JonasAlfredsson** [comment]
Hi plohoj,

I have made it difficult to allow HTTP just because I do believe one should strife for secure connections all the time.
However, I know there are times when this becomes cumbersome, and there is nothing stopping you from using HTTP with this image, one selling point of it is that we do minimal alterations from the parent Nginx image.

To disable the "forceful" redirect you just have to mount your configs to `/etc/nginx/conf.d/` instead of `/etc/nginx/user_conf.d/` so you overwrite the [`redirector.conf`](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/src/nginx_conf.d/redirector.conf) file (if you read the docs it is mentioned [here](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/good_to_know.md#the-user_confd-folder)).
