### ISSUE TITLE
Possibility to download certificate by https

### ISSUE THREAD

**Issue by Gugu04** [JonasAlfredsson/docker-nginx-certbot#151]
Why it does a fetch to download the certificate by http and not by https ?

example
![image](https://user-images.githubusercontent.com/54090651/197239656-bea5e2f8-08f7-42ac-85f3-e7b7e12348e4.png)

**There is the possibility of changing it so that it downloads the certificate by https and not by http**

**Comment by JonasAlfredsson** [comment]
That message is from the Let's Encrypt servers. 
Your local certbot client places a unique file in that /.well-known/ folder, and then the Let's Encrypt servers try to find this file by going to the requested domain name + that extra path. If it finds the file they can know you own the domain and will sign the certificate for you. 

The reason to why the Let's Encrypt servers connect to you hover HTTP is because you do not yet have HTTPS since that is what certbot is trying to set up.

**Comment by JonasAlfredsson** [comment]
If port 80 is completely blocked (by your ISP for example) then you shuold probably look into the [ALPN-01](https://letsencrypt.org/docs/challenge-types/#tls-alpn-01) challenge type, but that is not something I support for the moment.

**Comment by Gugu04** [comment]
@JonasAlfredsson  **thank you very much.. it has become clearer to me how letsencrypt works**
