### ISSUE TITLE
Support for Armv8

### ISSUE THREAD

**Issue by clragon** [JonasAlfredsson/docker-nginx-certbot#158]
I like hosting my site on my raspberry pi (3B, Bullseye). 
The architecture for that would be aarch64 (Armv8). 
Alpine itself does have images for that architecture.
Would it be possible to support it here as well?

**Comment by JonasAlfredsson** [comment]
Hi clargon,

I build [both](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/.github/workflows/build_latest.yml#L41) Alpine and Debian with the `amd64` and `arm64` [platforms](https://docs.docker.com/build/building/multi-platform/), so if it is a 64 bit arm device it should work.

However, if it is 32 bit I only support the Debian image since Alpine has given me so much trouble:
- https://github.com/JonasAlfredsson/docker-nginx-certbot/commit/3fc2d64d3f20aa2163598e57e59a95a79cde1f37
- https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/70
- https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/77
- https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/109

**Comment by clragon** [comment]
I see, this does indeed work. I was a bit confused because other images like alpine normally include a dedicated image tagged `linux/arm64/v8`. Thank you for your work.

**Comment by JonasAlfredsson** [comment]
Yeah, sometimes you have to do it like that in case the build steps are just too different between the architectures. Else I find it much more intuitive to have it like this where each tag is built for all supported arches. 

You can look at the tags on Docker Hub to see what is supported on each specific tag: https://hub.docker.com/r/jonasal/nginx-certbot/tags

But glad it worked out for you :)
