### ISSUE TITLE
Wrong link in docker hub page

### ISSUE THREAD

**Issue by edmondyip** [JonasAlfredsson/docker-nginx-certbot#180]
https://hub.docker.com/r/jonasal/nginx-certbot

Docker compose example file url is wrong

**Comment by JonasAlfredsson** [comment]
Hi edmondyip,

Yeah, I have heard this mentioned before, and that is because I use relative paths in my documentation here in GitHub and I just clone the main README to DockerHub. However, this breaks the relative links, so I should perhaps look into just redirecting everyone to GitHub instead of having a copy of the basic README on DockerHub as well.
