### ISSUE TITLE
Nginx alpine image

### ISSUE THREAD

**Issue by tudddorrr** [JonasAlfredsson/docker-nginx-certbot#35]
Hey, just wanted to check, is there any reason why the Nginx base image doesn't use the alpine version?

**Comment by JonasAlfredsson** [comment]
Hi tudddorrr,

There is no strong reason for why Apline is not used but I will list some of the reasons:

- [Staticfloat's image](https://github.com/staticfloat/docker-nginx-certbot) was based on the mainline/Debian release of Nginx, and my repository was originally a fork of it so it has remained that way :)
- My default working environment is Debian, so that is what I am most comfortable working with. 
- You are also the first one to ask about an Alpine version, so I have not really had to give it much thought up until now. :)
- Nginx seem to indicate that Debian is their primary platform since anything "Alpine" needs "-alpine" attached to the tag.

But if there is a strong desire to provide an Alipne version as well, then I'll see what can be done.

**Comment by tudddorrr** [comment]
That all makes sense thanks for letting me know. It's not a big deal really, I was just a bit curious. Cheers.

**Comment by JonasAlfredsson** [comment]
Hey, I just wanted to ping you and say that an Alpine version should now be available. 
Check out [issue 42](https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/42) for more details :)

**Comment by tudddorrr** [comment]
That was quick, thanks Jonas!

**Comment by JonasAlfredsson** [comment]
No problem, it was a fun challenge :)

I have only had time to do some basic testing of the new image, so if you start using this one would you be so kind and comment in #42 if it works for your use case or if something needs to be fixed? 
Thanks in advance :)

**Comment by tudddorrr** [comment]
Will do!
