### ISSUE TITLE
Not getting a secured connection

### ISSUE THREAD

**Issue by GnidaKid69** [JonasAlfredsson/docker-nginx-certbot#75]
Hello, I've followed the steps and tried installing an SSL certificate and Nginx server gave me an output, which said "Successfully received certificate." and "Found all the necessary files for '/etc/nginx/conf.d/server.conf.nokey', enabling..."
So basically it gave me no errors, but still connection was not secured and I was getting warnings on my browser while visiting the website. I tried checking it on "why no padlock" and here are the results. I don't understand how to fix these issues, so if you could please help me.
https://www.whynopadlock.com/results/44ea7814-5f06-4760-93c0-2ce2d5f1fca5

**Comment by JonasAlfredsson** [comment]
Could you please also provide the config file you are using.

**Comment by GnidaKid69** [comment]
`server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;

    # Domain names this server should respond to.
    server_name cryptospace.ge www.cryptospace.ge;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/cryptospace/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/cryptospace/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/cryptospace/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://free:8080;
  }
}`

**Comment by JonasAlfredsson** [comment]
Can you also post what kind of envionment variable you have set.
Because I think you have `STAGING=1` set since you get the following line in the report:

```
Certificate Issuer
    (STAGING) Let's Encrypt
```

This certificate is not a *production* certificate, which means that all traffic is properly encrypted but you should not use this when you want to do things for real. This is explained in the [Initial Testing](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/good_to_know.md#initial-testing) section.

**Comment by GnidaKid69** [comment]
That was the issue. Thank you
