### ISSUE TITLE
typo in example docker compose file

### ISSUE THREAD

**Issue by koppishere** [JonasAlfredsson/docker-nginx-certbot#87]
Thanks for the repo! I believe I have found a typo in the example docker compose file

currently
------
version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:

should be (extra ./ before nginx_secrets)
------
version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d

volumes:
  nginx_secrets:

**Comment by JonasAlfredsson** [comment]
Hi koppishere,

Thank you for opening an issue, but there is actually no typo here :)
In Docker there are 3 different types of mounts: [bind-mounts, volumes & tmpfs](https://docs.docker.com/storage/bind-mounts/). The differences are explained in the link, but in this compose file the `./user_conf.d` folder is a bind-mount, while the `nginx_secrets` (without leading `./`) is a volume mount. You can also see it defined at the very bottom of the file as well:

```yaml
volumes:
  nginx_secrets:
```
So this example is working as intended displaying both options. 

---

P.S. In order to paste yaml code in a easier to read format you can do like this:
``````
```yaml
volumes:
   nginx_secrets:
```
``````
