### ISSUE TITLE
Update worker_processes

### ISSUE THREAD

**Issue by jasonsinclair5** [JonasAlfredsson/docker-nginx-certbot#95]
I'm getting a ton of "1024 worker_connections are not enough" errors in my log. However, the worker_connections setting is located under /etc/nginx/nginx.conf and not mapped so I cannot modify it. How would I go about making changes to the worker_connections config under events ?

**Comment by JonasAlfredsson** [comment]
This is a problem more related to the parent image, but we can take a look at their entrypoint script called [30-tune-worker-processes.sh](https://github.com/nginxinc/docker-nginx/blob/master/entrypoint/30-tune-worker-processes.sh) which changes the worker processes to something they think your system is capable of handling. According to [this](https://www.techrepublic.com/article/3-quick-steps-to-optimize-the-performance-of-your-nginx-server/) it is preferred to increase that instead of connections, however, there is nothing stopping you from adding your own custom entrypoint script which might include something like this instead:

```bash
#!/bin/bash

sed -i -r 's/^(\s*worker_connections\s+)[^;]*(;.*)$/\1<your_number>\2/' /etc/nginx/nginx.conf
```

where you just change to the number of connections you want. So if I would want to double it (from the [default of 1024](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/nginx_tips.md#how-nginx-loads-configs)) I would write this:

```bash
#!/bin/bash

sed -i -r 's/^(\s*worker_connections\s+)[^;]*(;.*)$/\12048\2/' /etc/nginx/nginx.conf
```

---

Do you mind me asking what kind of website you are running to be hitting these limits?

**Comment by jasonsinclair5** [comment]
Ok, I will review that and give it a shot. I appreciate the quick reply! The website running behind this is an old XML API for an E-commerce site that connects into an ERP system. We are testing to remove public-facing access to the old and outdated IIS server. It's currently being transitioned to a more efficient Python Celery API, but we still have a couple things using it.

**Comment by JonasAlfredsson** [comment]
Sure thing!
Good luck, and please update this issue if it worked or not :)

**Comment by JonasAlfredsson** [comment]
Did my suggestion work, or would you like some further assistance?

**Comment by jasonsinclair5** [comment]
Apologies...I ended up not changing the worker processes. After digging
some more I found out the Python script they were testing was sending too
many requests causing this error. Once they shut it down, it has been
stable now. One additional question I do have. I would like to setup
conditional logging. IE: 200 requests ignored, 400+ logged. I see you can
set that up in the nginx.conf file as well. Would that be something that
could be achieved through the entrypoint scripts?

**Comment by JonasAlfredsson** [comment]
You can do basically anything with entrypoint scripts, but there might be a simpler way. Would you mind posting exactly what settings you would like to introduce and I can see if I can help you.

**Comment by jasonsinclair5** [comment]
Sure thing. Let me dig up my notes and find what I was trying to do. Thanks
again for all your help!

**Comment by JonasAlfredsson** [comment]
Do you need any more help or should I close this issue?

**Comment by jasonsinclair5** [comment]
Apologies...the log4shell vulnerability side-tracked me for some time. What I wanted to do was something like mentioned in this forum:

https://stackoverflow.com/questions/39708347/nginx-conditional-logging-doesnt-work

For example, something like this in the http portion:

map $status $anyerr {
    ~^[45]  1;
    default 0;
}

So then I can add these to the server portion of the config files:

access_log  /var/log/nginx/access.log  main;
access_log  /var/log/nginx/access_400.log full if=$anyerr;

Let me know if that makes sense, or whether that's possible. As always, I appreciate the help!

**Comment by JonasAlfredsson** [comment]
Yeah, that bug has kept me busy as well so I understand :)

I don't see any problem with you adding this. I have a section where I explain how Nginx [loads configs](https://github.com/JonasAlfredsson/docker-nginx-certbot/blob/master/docs/nginx_tips.md#how-nginx-loads-configs), which might be of interest for you to read. Then you could just create a file called `00-statusmapper.conf` that only contains 

```
map $status $anyerr {
  ~^[45] 1;
  default 0;
}
```

and then just add the loging statements to the sever blocks you want. Or you can add the above posted lines to this file as well and have them apply to all coming server blocks.

**Comment by jasonsinclair5** [comment]
Perfect! I will go ahead and give that a shot. Thanks again for all the help!
